// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrfcHsCkPxD7ACh7gmmUuaiADavmsiCCA',
    appId: '1:626395383987:web:06b15fb3812bc806a608c6',
    messagingSenderId: '626395383987',
    projectId: 'inventory-app-b78c9',
    authDomain: 'inventory-app-b78c9.firebaseapp.com',
    storageBucket: 'inventory-app-b78c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClTShlqx74LiIIJUj4qkumkyVQPGLOQmE',
    appId: '1:626395383987:android:ab5335943867c56da608c6',
    messagingSenderId: '626395383987',
    projectId: 'inventory-app-b78c9',
    storageBucket: 'inventory-app-b78c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT4kIDTVaTr1YwZNIHuUiETvR3wJ1-T74',
    appId: '1:626395383987:ios:c4681cb437686421a608c6',
    messagingSenderId: '626395383987',
    projectId: 'inventory-app-b78c9',
    storageBucket: 'inventory-app-b78c9.appspot.com',
    iosClientId:
        '626395383987-1vlt9h412puektm4iqklq93p4dd2qr01.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT4kIDTVaTr1YwZNIHuUiETvR3wJ1-T74',
    appId: '1:626395383987:ios:c4681cb437686421a608c6',
    messagingSenderId: '626395383987',
    projectId: 'inventory-app-b78c9',
    storageBucket: 'inventory-app-b78c9.appspot.com',
    iosClientId:
        '626395383987-1vlt9h412puektm4iqklq93p4dd2qr01.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2firebase',
  );
}
